version: "3"

services:
  server:
    build: .
    env_file:
      - ./server/.env
    volumes:
      - ./server:/server
    depends_on:
      - db
    environment:

    ports:
      - "4000:4000"
    command: node --inspect=0.0.0.0:9229 ./bin/www
  db:
    image: postgres:14.0-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: