import { generate } from 'src/utils/generators';

export const users: UserDTO[] = [
	{
		userID: 'fe51k85',
		username: 'Bret',
		avatar: generate.avatar(),
		preferedDistance: 40,
		socketID: '',
		room: '',
	},
	{
		userID: 'fe5dk15',
		username: 'Antonette',
		avatar: generate.avatar(),
		preferedDistance: 40,
		socketID: '',
		room: '',
	},
	{
		userID: 'fe51k2q',
		username: 'Samantha',
		avatar: generate.avatar(),
		preferedDistance: 40,
		socketID: '',
		room: '',
	},
	{
		userID: 'vew1281',
		username: 'Karianne',
		avatar: generate.avatar(),
		preferedDistance: 40,
		socketID: '',
		room: '',
	},
	{
		userID: 'aed1k11',
		username: 'Kamren',
		avatar: generate.avatar(),
		preferedDistance: 40,
		socketID: '',
		room: '',
	},
	{
		userID: '12s1ka5',
		username: 'Leopoldo_Corkery',
		avatar: generate.avatar(),
		preferedDistance: 40,
		socketID: '',
		room: '',
	},
	{
		userID: 're5bsa5',
		username: 'Elwyn.Skiles',
		avatar: generate.avatar(),
		preferedDistance: 40,
		socketID: '',
		room: '',
	},
	{
		userID: 'ee51185',
		username: 'Maxime_Nienow',
		avatar: generate.avatar(),
		preferedDistance: 40,
		socketID: '',
		room: '',
	},
	{
		userID: 'fx52kk5',
		username: 'Delphine',
		avatar: generate.avatar(),
		preferedDistance: 40,
		socketID: '',
		room: '',
	},
	{
		userID: '1ee1k25',
		username: 'Moriah.Stanton',
		avatar: generate.avatar(),
		preferedDistance: 40,
		socketID: '',
		room: '',
	},
];
